### ISSUE TITLE
Please remove references to BFKit-Swift

### ISSUE THREAD

**Issue by FabrizioBrancati** [phpmaple/Stick-Hero-Swift#1]
I don't care that you have copy the first part of your README from the one of BFKit-Swift, but please, remove the alt tag of your image that references to BFKit-Swift ahah

It's in the first line of your README
`<p align="center"><img src="http://share.koofrank.com/IMG_0604.PNG" alt="BFKit Swift Banner"></p>`

**Comment by phpmaple** [comment]
BFKit-Swift is very nice, Please don't mind my mistake, I have removed, thx

**Comment by FabrizioBrancati** [comment]
Don't worry :+1:
